version: "3.5"
services:
  hive:
    image: mpolatcan/hive:2.3.7-hadoop-2.7.7-java8
    container_name: hive
    hostname: hive
    environment:
      HADOOP_DAEMONS: |
        namenode
        datanode
