config_loader_sh_template: |
  #!/usr/bin/env bash

  function load_config() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "\t<property>\n\t\t<name>$1</name>\n\t\t<value>$2</value>\n\t</property>\n" >> "${{HIVE_CONF_DIR}}/$3"
      fi
  }}

  function load_config_with_opt() {{
      if [[ "$2" != "NULL" ]]
          then
              printf "\t<property>\n\t\t<name>$1</name>\n\t\t<value>$3</value>\n\t</property>\n" >> "${{HIVE_CONF_DIR}}/$5"
      else
          printf "\t<property>\n\t\t<name>$1</name>\n\t\t<value>$4</value>\n\t</property>\n" >> "${{HIVE_CONF_DIR}}/$5"
      fi
  }}

  {load_fn_calls}

config_files:
  - path: hive_configs/hive-site.yml
    filename: hive-site.xml

output_dir: ../../setup